Document: pykolab
Title: Debian pykolab Manual
Author: <insert document author here>
Abstract: This manual describes what pykolab is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pykolab/pykolab.sgml.gz

Format: postscript
Files: /usr/share/doc/pykolab/pykolab.ps.gz

Format: text
Files: /usr/share/doc/pykolab/pykolab.text.gz

Format: HTML
Index: /usr/share/doc/pykolab/html/index.html
Files: /usr/share/doc/pykolab/html/*.html
